[package]
name = "deptyr"
version = "0.1.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]

[dependencies]
nix = { git = "https://github.com/antifuchs/nix.git", branch = "pselect" }
clap = "2.31.2"
failure = "0.1.1"
sendfd = "0.1.0"
libc = "0.2.40"
owned-fd = "0.1.0"